<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<table>
    <thead></table>
    <table>
        <thead>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th><b>REGISTRO NOTAS</b></th>
        </tr>
        </thead>
    </table>
    <table>
        <thead>
        <tr>
            <th></th>
            <th></th>
            <th>PRIMER BIMESTRE</th>
            <th></th>
            <th></th>   
            <th>Año academico:</th>
            <th></th>
            <th>2015</th>
        </tr>
        </thead>
    </table>
    <table>
        <thead>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th><b>PRIMER BIMESTRE</b></th>
        </tr>
        </thead>
    </table>
    <table>
        <thead>
        <tr>
            <th></th>
            <th></th>
            <th><b>Grado</b></th>
            <th></th>
            <th></th>
            <th></th>
            <th><b>Seccion</b></th>
            <th></th>
            <th></th>
            <th><b>Area</b></th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td>Primer Grado de Primaria</td>
                <td></td>
                <td></td>
                <td></td>
                <td>A</td>
                <td></td>
                <td></td>
                <td>Educacion Fisica</td>
            </tr>
        </tbody>
    </table>
    <table>
        <thead>
        <tr>
            <th></th>
            <th></th>
            <th><b>CODTRA</b></th>
            <th></th>
            <th></th>
            <th><b>PROFESOR</b></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th><b>FECHA</b></th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td>S136</td>
                <td></td>
                <td></td>
                <td>JUAN SANTOS</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>12/02/2016</td>
            </tr>
        </tbody>
    </table>
    <table>
        <thead>
        <tr>
            <th></th>
            <th></th>
            <th><b>No</b></th>
            <th><b>Apellidos y Nombres</b></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th><b>Co</b></th>
            <th><b>Do</b></th>
            <th><b>Co</b></th>
            <th><b>Ac</b></th>
            <th><b>PR</b></th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td>1</td>
                <td>Lujan Carranza Michael Alexander</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>1</td>
                <td>Lujan Carranza Michael Alexander</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>1</td>
                <td>Lujan Carranza Michael Alexander</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>1</td>
                <td>Lujan Carranza Michael Alexander</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>1</td>
                <td>Lujan Carranza Michael Alexander</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>1</td>
                <td>Lujan Carranza Michael Alexander</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>1</td>
                <td>Lujan Carranza Michael Alexander</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>1</td>
                <td>Lujan Carranza Michael Alexander</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>1</td>
                <td>Lujan Carranza Michael Alexander</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
                <td>20</td>
            </tr>
        </tbody>
    </table>
</body>
</html>